#include <stdio.h> 

/* 
	CODIGO EM C CRIADO POR HENRIQUE MARCHI LANGE E DESNECESSARIAMENTE COMENTADO; 
	O CODIGO ABAIXO ACESSA O METODO DE SAIDA PARAO DO WINDOWS PARA ESCREVER NA TELA "HELLO WORLD"; 
	O CODIGO ESTA SOBRE LICENSA GPL, PORTANTO AO USA-LO EM PROJETOS DEVERAO CITAR SEU AUTOR!!!! 
*/

int main(){
	printf ("Hello Git!!\n");
	printf ("Preferia usar email D: \n"); 
	printf ("Mas ok! \n"); 
	return 0; 
}