# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\gabri\Desktop\projeto_especializado\Projeto_Especializado\Sources\Windows\UI\\template_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.graphics_view = QtWidgets.QGraphicsView(Dialog)
        self.graphics_view.setGeometry(QtCore.QRect(90, 60, 480, 360))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphics_view.sizePolicy().hasHeightForWidth())
        self.graphics_view.setSizePolicy(sizePolicy)
        self.graphics_view.setMinimumSize(QtCore.QSize(480, 360))
        self.graphics_view.setMaximumSize(QtCore.QSize(480, 360))
        self.graphics_view.setStyleSheet("border-color: rgb(100, 100, 100);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.graphics_view.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.graphics_view.setObjectName("graphics_view")
        self.label_33 = QtWidgets.QLabel(Dialog)
        self.label_33.setGeometry(QtCore.QRect(30, 20, 591, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"color: rgb(50, 50, 50);\n"
"border-color: rgb(100, 100, 100);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.reset_push_button = QtWidgets.QPushButton(Dialog)
        self.reset_push_button.setGeometry(QtCore.QRect(120, 430, 151, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_push_button.sizePolicy().hasHeightForWidth())
        self.reset_push_button.setSizePolicy(sizePolicy)
        self.reset_push_button.setMaximumSize(QtCore.QSize(999999, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.reset_push_button.setFont(font)
        self.reset_push_button.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(235, 235, 235);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.reset_push_button.setObjectName("reset_push_button")
        self.finish_push_button = QtWidgets.QPushButton(Dialog)
        self.finish_push_button.setEnabled(False)
        self.finish_push_button.setGeometry(QtCore.QRect(310, 430, 151, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finish_push_button.sizePolicy().hasHeightForWidth())
        self.finish_push_button.setSizePolicy(sizePolicy)
        self.finish_push_button.setMaximumSize(QtCore.QSize(999999, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.finish_push_button.setFont(font)
        self.finish_push_button.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(235, 235, 235);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.finish_push_button.setObjectName("finish_push_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_33.setText(_translate("Dialog", "Escolha do template"))
        self.reset_push_button.setText(_translate("Dialog", "Resetar pontos"))
        self.finish_push_button.setText(_translate("Dialog", "Finalizar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
